



export NLS_LANG="LATIN AMERICAN SPANISH_AMERICA.WE8ISO8859P1"

FNDLOAD apps/aY1bMB3qd O Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct US_XX_AP_EFT_TRANS_BNKFILE.ldt PROGRAM APPLICATION_SHORT_NAME="XBOL" CONCURRENT_PROGRAM_NAME="XX_AP_EFT_TRANS_BNKFILE"




export NLS_LANG="American_America.WE8ISO8859P1"
 

