ALTER TABLE BOLINF.XX_SV_AP_EPAYMENT_DETAIL
 DROP PRIMARY KEY CASCADE;
DROP TABLE BOLINF.XX_SV_AP_EPAYMENT_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE BOLINF.XX_SV_AP_EPAYMENT_DETAIL
(
  ID_FILE_FORMAT     NUMBER,
  ID_MASTER          NUMBER,
  FIELD_NAME         VARCHAR2(150 BYTE),
  TYPE_VALUE         VARCHAR2(50 BYTE),
  CONSTANT_VALUE     VARCHAR2(4000 BYTE),
  SECUENCE           NUMBER,
  MAX_VALUE_LENGHT   NUMBER,
  START_POSITION     NUMBER,
  END_POSITION       NUMBER,
  DATA_TYPE          VARCHAR2(50 BYTE),
  FORMAT             VARCHAR2(50 BYTE),
  PADDING_CHARACTER  VARCHAR2(1 BYTE),
  DIRECTION_PADDING  VARCHAR2(50 BYTE),
  SQL_STATEMENT      VARCHAR2(4000 BYTE),
  NEEDS_PADDING      VARCHAR2(1 BYTE),
  PART_OF_FILE       VARCHAR2(50 BYTE),
  CREATED_BY         NUMBER,
  CREATION_DATE      DATE,
  LAST_UPDATED_BY    NUMBER,
  LAST_UPDATE_DATE   DATE
)
TABLESPACE XBOLDATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX BOLINF.XX_SV_AP_EPAYMENT_DETAIL_U1 ON BOLINF.XX_SV_AP_EPAYMENT_DETAIL
(ID_FILE_FORMAT)
LOGGING
TABLESPACE XBOLINDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM XX_SV_AP_EPAYMENT_DETAIL;

CREATE PUBLIC SYNONYM XX_SV_AP_EPAYMENT_DETAIL FOR BOLINF.XX_SV_AP_EPAYMENT_DETAIL;


ALTER TABLE BOLINF.XX_SV_AP_EPAYMENT_DETAIL ADD (
  CONSTRAINT XX_SV_AP_EPAYMENT_DETAIL_U1
 PRIMARY KEY
 (ID_FILE_FORMAT)
    USING INDEX 
    TABLESPACE XBOLINDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          1M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON BOLINF.XX_SV_AP_EPAYMENT_DETAIL TO APPS WITH GRANT OPTION;

GRANT SELECT ON BOLINF.XX_SV_AP_EPAYMENT_DETAIL TO RAC_ACCNT;

GRANT SELECT ON BOLINF.XX_SV_AP_EPAYMENT_DETAIL TO RAC_COM;

GRANT SELECT ON BOLINF.XX_SV_AP_EPAYMENT_DETAIL TO RAC_FIN;

GRANT SELECT ON BOLINF.XX_SV_AP_EPAYMENT_DETAIL TO RAC_SUP;


SET DEFINE OFF;
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (1, 1, 'Cuenta Bancaria', 'DINAMIC', NULL, 
    10, NULL, 1, 15, 'STRING', 
    NULL, '0', 'LEFT', 'SELECT REPLACE (REPLACE (BANK_ACCOUNT_NUM, ''-'', ''''), '' '', '''') BANK_ACCOUNT_NUM   FROM (  SELECT EBA.BANK_ACCOUNT_NUM, PIU.ORDER_OF_PREFERENCE             FROM ap.ap_supplier_sites_all ss,                  ap.ap_suppliers sp,                  iby.iby_external_payees_all epa,                  iby.iby_pmt_instr_uses_all piu,                  iby.iby_ext_bank_accounts eba,                  ap.ap_checks_all ch,                  apps.ce_banks_v ib,                  ce.ce_bank_acct_uses_all ibu,                  ce.ce_bank_accounts iba,                  ce.ce_payment_documents idc            WHERE     CH.CHECK_ID = :IDCHECK                  AND ss.org_id = CH.ORG_ID                  AND SP.VENDOR_ID = nvl(CH.REMIT_TO_SUPPLIER_ID,  cH.VENDOR_ID)                  and SS.VENDOR_SITE_ID = nvl(CH.REMIT_TO_SUPPLIER_SITE_ID , CH.VENDOR_SITE_ID)                  AND ss.vendor_site_id = epa.supplier_site_id                  AND epa.ext_payee_id = piu.ext_pmt_party_id                  AND piu.instrument_id = eba.ext_bank_account_id                  AND CH.PAYMENT_DOCUMENT_ID = iDC.PAYMENT_DOCUMENT_ID                  AND idc.INTERNAL_BANK_ACCOUNT_ID = ibu.BANK_ACCOUNT_ID                  AND ibu.BANK_ACCOUNT_ID = iba.BANK_ACCOUNT_ID                  AND iba.BANK_ID = ib.BANK_PARTY_ID                  AND ib.BANK_PARTY_ID = EBA.BANK_ID /*Esto es para que la cuenta que traiga sea del mimo banco*/                  AND NVL (                         PIU.                         END_DATE,                         SYSDATE) >=                         SYSDATE         ORDER BY ORDER_OF_PREFERENCE ASC)  WHERE ROWNUM = 1                                   /*La de mayor prioridad */', 'Y', 
    'TRX', 3129, TO_DATE('04/15/2013 09:29:21', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/20/2013 10:09:04', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (2, 1, 'Tipo de Cuenta', 'DINAMIC', NULL, 
    20, NULL, NULL, NULL, 'STRING', 
    NULL, NULL, NULL, 'SELECT BANK_ACCOUNT_TYPE   FROM (  SELECT DECODE (EBA.BANK_ACCOUNT_TYPE, ''CHECKING'', ''3'', ''SAVING'', ''4'',   ''SAVINGS'', ''4'',    ''2'', ''4'',   ''X'')                     BANK_ACCOUNT_TYPE,                  PIU.ORDER_OF_PREFERENCE             FROM ap.ap_supplier_sites_all ss,                  ap.ap_suppliers sp,                  iby.iby_external_payees_all epa,                  iby.iby_pmt_instr_uses_all piu,                  iby.iby_ext_bank_accounts eba,                  ap.ap_checks_all ch,                  apps.ce_banks_v ib,                  ce.ce_bank_acct_uses_all ibu,                  ce.ce_bank_accounts iba,                  ce.ce_payment_documents idc            WHERE     CH.CHECK_ID = :IDCHECK                  AND nvl(CH.REMIT_TO_SUPPLIER_ID,CH.VENDOR_ID) = SP.VENDOR_ID                  and nvl(CH.REMIT_TO_SUPPLIER_SITE_ID,CH.VENDOR_SITE_ID) = SS.VENDOR_SITE_ID                  AND ss.vendor_site_id = epa.supplier_site_id                  AND epa.ext_payee_id = piu.ext_pmt_party_id                  AND piu.instrument_id = eba.ext_bank_account_id                  AND CH.PAYMENT_DOCUMENT_ID = iDC.PAYMENT_DOCUMENT_ID                  AND idc.INTERNAL_BANK_ACCOUNT_ID = ibu.BANK_ACCOUNT_ID                  AND ibu.BANK_ACCOUNT_ID = iba.BANK_ACCOUNT_ID                  AND iba.BANK_ID = ib.BANK_PARTY_ID                  AND ib.BANK_PARTY_ID = EBA.BANK_ID /*Esto es para que la cuenta que traiga sea del mimo banco*/                  AND NVL (                         PIU.                         END_DATE,                         SYSDATE) >=                         SYSDATE         ORDER BY ORDER_OF_PREFERENCE ASC)  WHERE ROWNUM = 1', NULL, 
    'TRX', 3129, TO_DATE('04/15/2013 09:29:21', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/20/2013 10:22:12', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (3, 1, 'Monto del Pago', 'DINAMIC', NULL, 
    30, NULL, NULL, NULL, 'STRING', 
    NULL, NULL, NULL, 'select trim(to_char(ch.AMOUNT,''9999999999.99''))   from apps.ap_checks_all ch  where ch.CHECK_ID = :IDCHECK    and PAYMENT_METHOD_CODE = ''EFT''    AND CH.VOID_DATE IS NULL', NULL, 
    'TRX', 3129, TO_DATE('04/15/2013 09:29:21', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/16/2013 09:14:19', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (72, 3, 'Number of Third Party Records', 'CONSTANT', '0', 
    630, NULL, 34, 48, 'STRING', 
    NULL, '0', 'RIGHT', NULL, 'Y', 
    'FOOTER', 3129, TO_DATE('05/03/2013 14:52:57', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/03/2013 14:52:57', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (73, 3, 'Number of Records Sent', 'DINAMIC', NULL, 
    640, NULL, 49, 63, 'STRING', 
    NULL, '0', 'LEFT', 'SELECT INVOICES + CHECKS TOTAL   FROM (SELECT COUNT (CH.CHECK_ID) CHECKS           FROM AP_CHECKS_ALL CH          WHERE 1 = 1            AND TRUNC (CH.CHECK_DATE) >=                   TRUNC (TO_DATE (:P_START_DATE, ''YYYY/MM/DD HH24:MI:SS'')) /*NOT NULL*/            AND TRUNC (CH.CHECK_DATE) <=                   TRUNC (TO_DATE (:P_END_DATE, ''YYYY/MM/DD HH24:MI:SS'')) /*NOT NULL*/            AND CH.PAYMENT_DOCUMENT_ID = :PAY_DOCUMENT /*NOT NULL*/            AND CH.AMOUNT BETWEEN NVL (:BASE_AMOUNT, CH.AMOUNT)                              AND NVL (:TOP_AMOUNT, CH.AMOUNT) /* PSBLY NULL*/            AND NVL (CH.CHECKRUN_ID, 1) =                          NVL (NVL (:IDCHECKRUN, CH.CHECKRUN_ID), 1) /* CASE 1*/            AND NVL (CH.DOC_SEQUENCE_VALUE, 1) >=                    NVL (NVL (:P_DOC_INI, CH.DOC_SEQUENCE_VALUE), 1) /* CASE 2*/            AND NVL (CH.DOC_SEQUENCE_VALUE, 1) <=                    NVL (NVL (:P_DOC_FIN, CH.DOC_SEQUENCE_VALUE), 1) /* CASE 2*/            AND CH.PAYMENT_METHOD_CODE = ''EFT''            AND NVL (CH.ATTRIBUTE14, ''NEW'') = ''NEW''            AND CH.VOID_DATE IS NULL),        (SELECT COUNT (IA.INVOICE_ID) INVOICES           FROM AP_INVOICE_PAYMENTS_ALL IPA,                AP_INVOICES_ALL IA,                AP_CHECKS_ALL CH          WHERE IPA.INVOICE_ID = IA.INVOICE_ID            AND IPA.CHECK_ID = CH.CHECK_ID            AND TRUNC (CH.CHECK_DATE) >=                   TRUNC (TO_DATE (:P_START_DATE, ''YYYY/MM/DD HH24:MI:SS'')) /*NOT NULL*/            AND TRUNC (CH.CHECK_DATE) <=                   TRUNC (TO_DATE (:P_END_DATE, ''YYYY/MM/DD HH24:MI:SS'')) /*NOT NULL*/            AND CH.PAYMENT_DOCUMENT_ID = :PAY_DOCUMENT /*NOT NULL*/            AND CH.AMOUNT BETWEEN NVL (:BASE_AMOUNT, CH.AMOUNT)                              AND NVL (:TOP_AMOUNT, CH.AMOUNT) /* PSBLY NULL*/            AND NVL (CH.CHECKRUN_ID, 1) =                          NVL (NVL (:IDCHECKRUN, CH.CHECKRUN_ID), 1) /* CASE 1*/            AND NVL (CH.DOC_SEQUENCE_VALUE, 1) >=                    NVL (NVL (:P_DOC_INI, CH.DOC_SEQUENCE_VALUE), 1) /* CASE 2*/            AND NVL (CH.DOC_SEQUENCE_VALUE, 1) <=                    NVL (NVL (:P_DOC_FIN, CH.DOC_SEQUENCE_VALUE), 1) /* CASE 2*/            AND CH.PAYMENT_METHOD_CODE = ''EFT''            AND NVL (CH.ATTRIBUTE14, ''NEW'') = ''NEW''            AND CH.VOID_DATE IS NULL)', NULL, 
    'FOOTER', 3129, TO_DATE('05/03/2013 14:52:57', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/06/2013 13:27:52', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (74, 3, 'Blank Characters', 'CONSTANT', '\E', 
    650, NULL, 64, 100, 'STRING', 
    NULL, 'E', 'RIGHT', NULL, 'Y', 
    'FOOTER', 3129, TO_DATE('05/03/2013 14:52:57', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/06/2013 13:28:47', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (31, 3, 'VEndor Address Line 2', 'DINAMIC', NULL, 
    210, NULL, 372, 406, 'STRING', 
    NULL, NULL, NULL, 'select replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(upper(HZ.ADDRESS1), CHR(13), null), CHR(10),null), ''Ú'', ''U''), ''Ó'', ''O''), ''Í'', ''I''), ''É'', ''E''), ''Á'', ''A''),''À'',''A''),''È'',''E''),''Ì'',''I''),''Ò'',''O''),''Ù'',''U''),''Ñ'',''N''),''#'','' ''),''@'','' ''),''^'','' ''),''*'','' ''),''%'','' ''),''&'','' ''),''\'','' ''),''|'','' ''),''!'','' ''),''~'','' ''),''?'','' ''),''}'','' ''),''{'','' ''),''['','' ''),'']'','' ''),chr(39),'' ''),''`'','' ''),''/'','' ''),''Ü'',''U'') address FROM ap.AP_CHECKS_ALL CH , ap.AP_SUPPLIERS SP ,ar.HZ_PARTIES HZ WHERE CH.CHECK_ID = :IDCHECK AND nvl(CH.REMIT_TO_SUPPLIER_ID, CH.VENDOR_ID) = SP.VENDOR_ID AND SP.PARTY_ID = HZ.PARTY_ID', NULL, 
    'TRX', 3129, TO_DATE('04/30/2013 15:13:11', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/27/2013 16:24:37', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (5, 2, 'Numero de Cuanta', 'DINAMIC', NULL, 
    10, NULL, NULL, NULL, 'STRING', 
    NULL, NULL, NULL, 'SELECT REPLACE (REPLACE (BANK_ACCOUNT_NUM, ''-'', ''''), '' '', '''')           BANK_ACCOUNT_NUM   FROM (  SELECT EBA.BANK_ACCOUNT_NUM, PIU.ORDER_OF_PREFERENCE             FROM ap.ap_supplier_sites_all ss,                  ap.ap_suppliers sp,                  iby.iby_external_payees_all epa,                  iby.iby_pmt_instr_uses_all piu,                  iby.iby_ext_bank_accounts eba,                  ap.ap_checks_all ch,                  apps.ce_banks_v ib,                  ce.ce_bank_acct_uses_all ibu,                  ce.ce_bank_accounts iba,                  ce.ce_payment_documents idc            WHERE     CH.CHECK_ID = :IDCHECK                  AND ss.org_id = CH.ORG_ID                  AND SP.VENDOR_ID = NVL (CH.REMIT_TO_SUPPLIER_ID, cH.VENDOR_ID)                  AND SS.VENDOR_SITE_ID =                         NVL (CH.REMIT_TO_SUPPLIER_SITE_ID, CH.VENDOR_SITE_ID)                  AND ss.vendor_site_id = epa.supplier_site_id                  AND epa.ext_payee_id = piu.ext_pmt_party_id                  AND piu.instrument_id = eba.ext_bank_account_id                  AND CH.PAYMENT_DOCUMENT_ID = iDC.PAYMENT_DOCUMENT_ID                  AND idc.INTERNAL_BANK_ACCOUNT_ID = ibu.BANK_ACCOUNT_ID                  AND ibu.BANK_ACCOUNT_ID = iba.BANK_ACCOUNT_ID                  AND iba.BANK_ID = ib.BANK_PARTY_ID                  AND ib.BANK_PARTY_ID = EBA.BANK_ID /*Esto es para que la cuenta que traiga sea del mimo banco*/                  AND NVL (                         PIU.                         END_DATE,                         SYSDATE) >=                         SYSDATE         ORDER BY ORDER_OF_PREFERENCE ASC)  WHERE ROWNUM = 1                                   /*La de mayor prioridad */', NULL, 
    'TRX', 3129, TO_DATE('04/22/2013 11:34:28', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/20/2013 10:11:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (39, 3, 'Third Party Type [for Non-Citibank Accounts]', 'DINAMIC', NULL, 
    290, NULL, 498, 499, 'STRING', 
    NULL, NULL, NULL, 'SELECT decode(ATTRIBUTE12,''071'',decode(BANK_ACCOUNT_TYPE,''SAVING'',''02'',''SAVINGS'',''02'',''2'',''02'',''CHECKING'',''01'',BANK_ACCOUNT_TYPE)) BANK_ACCOUNT_TYPE  FROM (   SELECT SS.ATTRIBUTE12,           SS.ATTRIBUTE13,          eba.bank_account_num,          PIU.ORDER_OF_PREFERENCE,          EBA.BANK_ACCOUNT_TYPE     FROM ap.ap_supplier_sites_all ss,          ap.ap_suppliers sp,          iby.iby_external_payees_all epa,          iby.iby_pmt_instr_uses_all piu,          iby.iby_ext_bank_accounts eba,          ap.ap_checks_all ch,          apps.ce_banks_v ib,          ce.ce_bank_acct_uses_all ibu,          ce.ce_bank_accounts iba,          ce.ce_payment_documents idc    WHERE     CH.CHECK_ID = :IDCHECK          AND SP.VENDOR_ID =  nvl(CH.REMIT_TO_SUPPLIER_ID, CH.VENDOR_ID) AND SS.VENDOR_SITE_ID = nvl(CH.REMIT_TO_SUPPLIER_SITE_ID, CH.VENDOR_SITE_ID)       AND ss.vendor_site_id = epa.supplier_site_id          AND epa.ext_payee_id = piu.ext_pmt_party_id          AND piu.instrument_id = eba.ext_bank_account_id          AND CH.PAYMENT_DOCUMENT_ID = iDC.PAYMENT_DOCUMENT_ID          AND idc.INTERNAL_BANK_ACCOUNT_ID = ibu.BANK_ACCOUNT_ID          AND ibu.BANK_ACCOUNT_ID = iba.BANK_ACCOUNT_ID          AND iba.BANK_ID = ib.BANK_PARTY_ID          AND ib.BANK_PARTY_ID = EBA.BANK_ID /*Esto es para que la cuenta que traiga sea del mimo banco*/          AND NVL (PIU.END_DATE, SYSDATE) >= SYSDATE ORDER BY ORDER_OF_PREFERENCE ASC) where rownum = 1', NULL, 
    'TRX', 3129, TO_DATE('04/30/2013 16:03:35', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/20/2013 11:34:34', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (18, 3, 'NIT', 'DINAMIC', NULL, 
    80, NULL, 49, 68, 'STRING', 
    NULL, 'E', 'RIGHT', 'select trim(REPLACE(NVL(sp.NUM_1099,''00000000000000'' ),''-'','''')) nit  FROM ap.ap_suppliers            sp , ap.ap_checks_all  ch where ch.CHECK_ID = :IDCHECK AND SP.VENDOR_ID =  nvl(CH.REMIT_TO_SUPPLIER_ID, CH.VENDOR_ID)', 'Y', 
    'TRX', 3129, TO_DATE('04/30/2013 14:03:02', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/20/2013 11:34:34', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (19, 3, 'Currency', 'CONSTANT', 'USD', 
    90, NULL, 69, 71, 'STRING', 
    NULL, NULL, NULL, NULL, NULL, 
    'TRX', 3129, TO_DATE('04/30/2013 14:03:02', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/30/2013 15:13:11', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (20, 3, 'Vendor Code', 'DINAMIC', NULL, 
    100, NULL, 72, 91, 'STRING', 
    NULL, 'E', 'RIGHT', 'SELECT SP.SEGMENT1 from ap_suppliers sp     , ap.AP_CHECKS_ALL CH WHERE SP.VENDOR_ID = nvl( CH.REMIT_TO_SUPPLIER_ID, CH.VENDOR_ID) AND CH.CHECK_ID = :IDCHECK', 'Y', 
    'TRX', 3129, TO_DATE('04/30/2013 15:13:11', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/20/2013 11:34:34', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (21, 3, 'Amount', 'DINAMIC', NULL, 
    110, NULL, 92, 106, 'STRING', 
    NULL, '0', 'LEFT', 'select AMOUNT*100  from apps.ap_checks_all ch  where ch.CHECK_ID = :IDCHECK', 'Y', 
    'TRX', 3129, TO_DATE('04/30/2013 15:13:11', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/30/2013 15:13:11', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (22, 3, 'Maturity Date (En blanco)', 'CONSTANT', '\E', 
    120, NULL, 107, 112, 'STRING', 
    NULL, 'E', 'RIGHT', NULL, 'Y', 
    'TRX', 3129, TO_DATE('04/30/2013 15:13:11', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/30/2013 15:13:11', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (23, 3, 'Description', 'DINAMIC', NULL, 
    130, NULL, 113, 147, 'STRING', 
    NULL, 'E', 'RIGHT', 'SELECT ''PAYMENT INVOICE : ''||LISTAGG(IA.INVOICE_NUM,'' , '') WITHIN GROUP (ORDER BY IA.INVOICE_NUM) invoices   FROM AP_CHECKS_ALL CH  ,AP_INVOICE_PAYMENTS_ALL IV  ,AP_INVOICES_ALL IA  WHERE CH.CHECK_ID = :IDCHECK    AND CH.CHECK_ID = IV.CHECK_ID    AND IV.INVOICE_ID = IA.INVOICE_ID', NULL, 
    'TRX', 3129, TO_DATE('04/30/2013 15:13:11', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/30/2013 15:13:11', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (25, 3, 'Description 3', 'CONSTANT', '\E', 
    150, NULL, 183, 217, 'STRING', 
    NULL, 'E', 'RIGHT', NULL, 'Y', 
    'TRX', 3129, TO_DATE('04/30/2013 15:13:11', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/30/2013 15:13:11', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (26, 3, 'Description 4', 'CONSTANT', '\E', 
    160, NULL, 218, 252, 'STRING', 
    NULL, 'E', 'LEFT', NULL, 'Y', 
    'TRX', 3129, TO_DATE('04/30/2013 15:13:11', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/30/2013 15:13:11', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (27, 3, 'Local Transaction Code', 'CONSTANT', '01', 
    170, NULL, 253, 254, 'STRING', 
    NULL, NULL, NULL, NULL, NULL, 
    'TRX', 3129, TO_DATE('04/30/2013 15:13:11', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/30/2013 15:13:11', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (28, 3, 'Customer Account Type', 'DINAMIC', NULL, 
    180, NULL, 255, 256, 'STRING', 
    NULL, NULL, NULL, 'select decode(BA.BANK_ACCOUNT_TYPE,''CHEKING'',''01'',''SAVING'',''02'',''01'')  FROM ce.CE_BANK_ACCOUNTS BA,   ce.CE_BANK_ACCT_USES_ALL BU,  ap.ap_checks_all ch WHERE BA.BANK_ACCOUNT_ID = BU.BANK_ACCOUNT_ID   and BU.BANK_ACCT_USE_ID = CH.CE_BANK_ACCT_USE_ID   and CH.CHECK_ID = :IDCHECK', NULL, 
    'TRX', 3129, TO_DATE('04/30/2013 15:13:11', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/30/2013 15:13:11', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (29, 3, 'Vendor Name', 'DINAMIC', NULL, 
    190, NULL, 257, 336, 'STRING', 
    NULL, NULL, NULL, 'SELECT     replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(upper(  nvl(CH.REMIT_TO_SUPPLIER_NAME, ch.VENDOR_NAME)    ), CHR(13), null), CHR(10),null), ''Ú'', ''U''), ''Ó'', ''O''), ''Í'', ''I''), ''É'', ''E''), ''Á'', ''A''),''À'',''A''),''È'',''E''),''Ì'',''I''),''Ò'',''O''),''Ù'',''U''),''Ñ'',''N''),''#'','' ''),''@'','' ''),''^'','' ''),''*'','' ''),''%'','' ''),''&'','' ''),''\'','' ''),''|'','' ''),''!'','' ''),''~'','' ''),''?'','' ''),''}'','' ''),''{'','' ''),''['','' ''),'']'','' ''),chr(39),'' ''),''`'','' ''),''/'','' ''),''Ü'',''U'')  vendor   FROM ap.AP_CHECKS_ALL CH   where ch.CHECK_ID = :IDCHECK', NULL, 
    'TRX', 3129, TO_DATE('04/30/2013 15:13:11', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/27/2013 16:24:37', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (32, 3, 'Citi', 'DINAMIC', NULL, 
    220, NULL, 407, 421, 'STRING', 
    NULL, NULL, NULL, 'SELECT HZ.CITY   FROM AP_CHECKS_ALL CH       ,AP_SUPPLIERS SP       ,ar.HZ_PARTIES HZ  WHERE CH.CHECK_ID = :IDCHECK    AND nvl( CH.REMIT_TO_SUPPLIER_ID, CH.VENDOR_ID) = SP.VENDOR_ID    AND SP.PARTY_ID = HZ.PARTY_ID', NULL, 
    'TRX', 3129, TO_DATE('04/30/2013 15:13:11', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/20/2013 11:34:34', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (33, 3, 'Departamento', 'CONSTANT', '\E', 
    230, NULL, 422, 423, 'STRING', 
    NULL, 'E', 'RIGHT', NULL, 'Y', 
    'TRX', 3129, TO_DATE('04/30/2013 15:13:11', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/06/2013 13:33:07', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (34, 3, 'Address More', 'CONSTANT', '\E', 
    240, NULL, 424, 435, 'STRING', 
    NULL, 'E', 'RIGHT', NULL, 'Y', 
    'TRX', 3129, TO_DATE('04/30/2013 15:13:11', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/06/2013 13:33:58', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (35, 3, 'Vendor Phone', 'CONSTANT', '\E', 
    250, NULL, 436, 451, 'STRING', 
    NULL, NULL, NULL, NULL, NULL, 
    'TRX', 3129, TO_DATE('04/30/2013 15:13:11', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/30/2013 15:13:11', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (36, 3, 'Third Party Bank Number', 'CONSTANT', '009', 
    260, NULL, 452, 454, 'STRING', 
    NULL, NULL, NULL, NULL, NULL, 
    'TRX', 3129, TO_DATE('04/30/2013 16:03:35', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/30/2013 16:03:35', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (37, 3, 'Third Party Bank Party', 'CONSTANT', '0001', 
    270, NULL, 455, 462, 'STRING', 
    NULL, NULL, NULL, NULL, NULL, 
    'TRX', 3129, TO_DATE('04/30/2013 16:03:35', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/30/2013 16:03:35', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (38, 3, 'Third Party Account Number [for Non-Citibank Accounts]', 'DINAMIC', NULL, 
    280, NULL, 463, 497, 'STRING', 
    NULL, 'E', 'RIGHT', 'SELECT decode(ATTRIBUTE12,''071'',REPLACE (REPLACE (bank_account_num, ''-'', ''''), '' '', ''''),'' '') bank_account_num  FROM (   SELECT SS.ATTRIBUTE12,           SS.ATTRIBUTE13,          eba.bank_account_num,          PIU.ORDER_OF_PREFERENCE,          EBA.BANK_ACCOUNT_TYPE     FROM ap.ap_supplier_sites_all ss,          ap.ap_suppliers sp,          iby.iby_external_payees_all epa,          iby.iby_pmt_instr_uses_all piu,          iby.iby_ext_bank_accounts eba,          ap.ap_checks_all ch,          apps.ce_banks_v ib,          ce.ce_bank_acct_uses_all ibu,          ce.ce_bank_accounts iba,          ce.ce_payment_documents idc    WHERE     CH.CHECK_ID = :IDCHECK         AND SP.VENDOR_ID =  nvl(CH.REMIT_TO_SUPPLIER_ID, CH.VENDOR_ID) AND SS.VENDOR_SITE_ID = nvl(CH.REMIT_TO_SUPPLIER_SITE_ID, CH.VENDOR_SITE_ID)         AND ss.vendor_site_id = epa.supplier_site_id          AND epa.ext_payee_id = piu.ext_pmt_party_id          AND piu.instrument_id = eba.ext_bank_account_id          AND CH.PAYMENT_DOCUMENT_ID = iDC.PAYMENT_DOCUMENT_ID          AND idc.INTERNAL_BANK_ACCOUNT_ID = ibu.BANK_ACCOUNT_ID          AND ibu.BANK_ACCOUNT_ID = iba.BANK_ACCOUNT_ID          AND iba.BANK_ID = ib.BANK_PARTY_ID          AND ib.BANK_PARTY_ID = EBA.BANK_ID /*Esto es para que la cuenta que traiga sea del mimo banco*/          AND NVL (PIU.END_DATE, SYSDATE) >= SYSDATE ORDER BY ORDER_OF_PREFERENCE ASC) where rownum = 1', 'Y', 
    'TRX', 3129, TO_DATE('04/30/2013 16:03:35', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/20/2013 11:34:34', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (40, 3, 'Bank Address', 'CONSTANT', '\E', 
    300, NULL, 500, 529, 'STRING', 
    NULL, NULL, NULL, NULL, NULL, 
    'TRX', 3129, TO_DATE('04/30/2013 16:03:35', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/30/2013 16:03:35', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (41, 3, 'Bank Entity', 'CONSTANT', '\E', 
    310, NULL, 530, 531, 'STRING', 
    NULL, NULL, NULL, NULL, NULL, 
    'TRX', 3129, TO_DATE('04/30/2013 16:03:35', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/30/2013 16:03:35', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (42, 3, 'Place Number', 'CONSTANT', '\E', 
    320, NULL, 532, 534, 'STRING', 
    NULL, NULL, NULL, NULL, NULL, 
    'TRX', 3129, TO_DATE('04/30/2013 16:03:35', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/30/2013 16:03:35', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (43, 3, 'Palce Name', 'CONSTANT', '\E', 
    330, NULL, 535, 548, 'STRING', 
    NULL, NULL, NULL, NULL, NULL, 
    'TRX', 3129, TO_DATE('04/30/2013 16:03:35', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/30/2013 16:03:35', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (44, 3, 'Branch Number', 'CONSTANT', '\E', 
    340, NULL, 549, 551, 'STRING', 
    NULL, NULL, NULL, NULL, NULL, 
    'TRX', 3129, TO_DATE('04/30/2013 16:03:35', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/30/2013 16:03:35', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (45, 3, 'Branch Name', 'CONSTANT', '\E', 
    350, NULL, 552, 570, 'STRING', 
    NULL, NULL, NULL, NULL, NULL, 
    'TRX', 3129, TO_DATE('04/30/2013 16:03:35', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/30/2013 16:03:35', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (46, 3, 'Fax Number', 'CONSTANT', '\E', 
    360, NULL, 571, 586, 'STRING', 
    NULL, NULL, NULL, NULL, NULL, 
    'TRX', 3129, TO_DATE('04/30/2013 16:03:35', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/30/2013 16:03:35', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (47, 3, 'Fax contact name', 'CONSTANT', '\E', 
    370, NULL, 587, 606, 'STRING', 
    NULL, NULL, NULL, NULL, NULL, 
    'TRX', 3129, TO_DATE('04/30/2013 16:03:35', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/30/2013 16:03:35', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (48, 3, 'Fax Department name', 'CONSTANT', '\E', 
    380, NULL, 607, 621, 'STRING', 
    NULL, NULL, NULL, NULL, NULL, 
    'TRX', 3129, TO_DATE('04/30/2013 16:03:35', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/30/2013 16:03:35', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (49, 3, 'Third Party Account number [for Citibank Accounts]', 'DINAMIC', NULL, 
    390, NULL, 622, 631, 'STRING', 
    NULL, 'E', 'LEFT', 'SELECT decode(ATTRIBUTE12,''072'',REPLACE (REPLACE (bank_account_num, ''-'', ''''), '' '', ''''),'' '')  FROM (   SELECT SS.ATTRIBUTE12,           SS.ATTRIBUTE13,          eba.bank_account_num,          PIU.ORDER_OF_PREFERENCE,          EBA.BANK_ACCOUNT_TYPE     FROM ap.ap_supplier_sites_all ss,          ap.ap_suppliers sp,          iby.iby_external_payees_all epa,          iby.iby_pmt_instr_uses_all piu,          iby.iby_ext_bank_accounts eba,          ap.ap_checks_all ch,          apps.ce_banks_v ib,          ce.ce_bank_acct_uses_all ibu,          ce.ce_bank_accounts iba,          ce.ce_payment_documents idc    WHERE     CH.CHECK_ID = :IDCHECK          AND ss.org_id = CH.ORG_ID          AND SP.VENDOR_ID = CH.VENDOR_ID          AND CH.VENDOR_ID = SS.VENDOR_ID          AND ss.vendor_site_id = epa.supplier_site_id          AND epa.ext_payee_id = piu.ext_pmt_party_id          AND piu.instrument_id = eba.ext_bank_account_id          AND CH.PAYMENT_DOCUMENT_ID = iDC.PAYMENT_DOCUMENT_ID          AND idc.INTERNAL_BANK_ACCOUNT_ID = ibu.BANK_ACCOUNT_ID          AND ibu.BANK_ACCOUNT_ID = iba.BANK_ACCOUNT_ID          AND iba.BANK_ID = ib.BANK_PARTY_ID          AND ib.BANK_PARTY_ID = EBA.BANK_ID /*Esto es para que la cuenta que traiga sea del mimo banco*/          AND NVL (PIU.END_DATE, SYSDATE) >= SYSDATE ORDER BY ORDER_OF_PREFERENCE ASC) where rownum = 1', 'Y', 
    'TRX', 3129, TO_DATE('04/30/2013 16:03:35', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/10/2013 15:51:19', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (11, 3, 'RECORDTYPE', 'CONSTANT', 'PAY', 
    10, NULL, 1, 3, 'STRING', 
    NULL, NULL, 'RIGHT', NULL, 'N', 
    'TRX', 3129, TO_DATE('04/29/2013 13:11:40', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/29/2013 13:11:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (12, 3, 'Customer Country Code', 'CONSTANT', '222', 
    20, NULL, 1, 3, 'STRING', 
    NULL, NULL, NULL, NULL, NULL, 
    'TRX', 3129, TO_DATE('04/29/2013 13:11:40', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/29/2013 13:11:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (13, 3, 'Customer Account Number', 'DINAMIC', NULL, 
    30, NULL, 7, 16, 'STRING', 
    NULL, '0', 'LEFT', 'select REPLACE(inba.BANK_ACCOUNT_NUM,''-'','''')   from  ap_checks_all          chk        ,CE_BANK_ACCT_USES_ALL  bua        ,ce_bank_accounts       inba        ,apps.CE_BANK_BRANCHES_V     BB  where  1=1    and  bua.BANK_ACCT_USE_ID   = chk.CE_BANK_ACCT_USE_ID    and  bua.BANK_ACCOUNT_ID    = inba.BANK_ACCOUNT_ID    and  bb.BRANCH_PARTY_ID     = inba.BANK_BRANCH_ID    AND  CHK.CHECK_ID = :IDCHECK', 'Y', 
    'TRX', 3129, TO_DATE('04/29/2013 13:11:40', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/13/2013 09:28:36', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (14, 3, 'Transaction Date', 'DINAMIC', NULL, 
    40, NULL, 17, 22, 'STRING', 
    NULL, NULL, NULL, 'SELECT to_char(CH.CHECK_DATE,''YYMMDD'')   FROM AP_CHECKS_ALL CH  WHERE CH.CHECK_ID = :IDCHECK', NULL, 
    'TRX', 3129, TO_DATE('04/29/2013 13:11:40', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/29/2013 13:11:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (15, 3, 'Transaction Code', 'DINAMIC', NULL, 
    50, NULL, 23, 25, 'STRING', 
    NULL, NULL, NULL, 'SELECT SS.ATTRIBUTE12  FROM AP_SUPPLIERS SUP, AP_SUPPLIER_SITES SS, AP_CHECKS_ALL CH WHERE SUP.VENDOR_ID = SS.VENDOR_ID   AND CH.VENDOR_SITE_ID = SS.VENDOR_SITE_ID   AND CH.CHECK_ID = :IDCHECK', NULL, 
    'TRX', 3129, TO_DATE('04/29/2013 13:11:40', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/03/2013 14:28:28', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (16, 3, 'Transaction Reference', 'DINAMIC', NULL, 
    60, NULL, 26, 40, 'STRING', 
    NULL, 'E', 'RIGHT', 'select CH.DOC_SEQUENCE_VALUE FROM    ap.ap_checks_all    ch WHERE CH.CHECK_ID =  :IDCHECK', 'Y', 
    'TRX', 3129, TO_DATE('04/29/2013 13:11:40', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/29/2013 16:06:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (17, 3, 'Transaction Sequence Number', 'SEQUENCE1', NULL, 
    70, NULL, 41, 48, 'NUMBER', 
    '99999999', '0', 'LEFT', NULL, 'Y', 
    'TRX', 3129, TO_DATE('04/29/2013 13:11:40', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/06/2013 13:40:47', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (6, 2, 'Nombre del Proveedor', 'DINAMIC', NULL, 
    20, NULL, NULL, NULL, 'STRING', 
    NULL, NULL, NULL, 'SELECT REPLACE (           REPLACE (              REPLACE (                 REPLACE (                    REPLACE (                       REPLACE (                          REPLACE (                             REPLACE (                                REPLACE (                                   REPLACE (                                      REPLACE (                                         REPLACE (UPPER ( nvl(CH.REMIT_TO_SUPPLIER_NAME, ch.VENDOR_NAME)),                                                  CHR (13),                                                  NULL),                                         CHR (10),                                         NULL),                                      ''Ú'',                                      ''U''),                                   ''Ó'',                                   ''O''),                                ''Í'',                                ''I''),                             ''É'',                             ''E''),                          ''Á'',                          ''A''),                       ''À'',                       ''A''),                    ''È'',                    ''E''),                 ''Ì'',                 ''I''),              ''Ò'',              ''O''),           ''Ù'',           ''U'')           vendor   FROM ap.AP_CHECKS_ALL CH  WHERE ch.CHECK_ID = :IDCHECK', NULL, 
    'TRX', 3129, TO_DATE('04/22/2013 11:34:28', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/20/2013 10:22:34', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (4, 1, 'Nombre del Proveedor', 'DINAMIC', NULL, 
    40, NULL, NULL, NULL, 'STRING', 
    NULL, NULL, NULL, 'SELECT REPLACE (           REPLACE (              REPLACE (                 REPLACE (                    REPLACE (                       REPLACE (                          REPLACE (                             REPLACE (                                REPLACE (                                   REPLACE (                                      REPLACE (                                         REPLACE (UPPER ( nvl(CH.REMIT_TO_SUPPLIER_NAME, ch.VENDOR_NAME)),                                                  CHR (13),                                                  NULL),                                         CHR (10),                                         NULL),                                      ''Ú'',                                      ''U''),                                   ''Ó'',                                   ''O''),                                ''Í'',                                ''I''),                             ''É'',                             ''E''),                          ''Á'',                          ''A''),                       ''À'',                       ''A''),                    ''È'',                    ''E''),                 ''Ì'',                 ''I''),              ''Ò'',              ''O''),           ''Ù'',           ''U'')           vendor   FROM ap.AP_CHECKS_ALL CH  WHERE ch.CHECK_ID = :IDCHECK', NULL, 
    'TRX', 3129, TO_DATE('04/15/2013 09:29:21', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/20/2013 10:22:12', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (30, 3, 'Vendor addres', 'DINAMIC', NULL, 
    200, NULL, 337, 371, 'STRING', 
    NULL, NULL, NULL, 'SELECT   replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(upper(HZ.ADDRESS1), CHR(13), null), CHR(10),null), ''Ú'', ''U''), ''Ó'', ''O''), ''Í'', ''I''), ''É'', ''E''), ''Á'', ''A''),''À'',''A''),''È'',''E''),''Ì'',''I''),''Ò'',''O''),''Ù'',''U''),''Ñ'',''N''),''#'','' ''),''@'','' ''),''^'','' ''),''*'','' ''),''%'','' ''),''&'','' ''),''\'','' ''),''|'','' ''),''!'','' ''),''~'','' ''),''?'','' ''),''}'','' ''),''{'','' ''),''['','' ''),'']'','' ''),chr(39),'' ''),''`'','' ''),''/'','' ''),''Ü'',''U'')  FROM AP_CHECKS_ALL CH       ,AP_SUPPLIERS SP       ,HZ_PARTIES HZ  WHERE CH.CHECK_ID = :IDCHECK    AND nvl( CH.REMIT_TO_SUPPLIER_ID, CH.VENDOR_ID) = SP.VENDOR_ID    AND SP.PARTY_ID = HZ.PARTY_ID', NULL, 
    'TRX', 3129, TO_DATE('04/30/2013 15:13:11', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/27/2013 16:24:37', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (24, 3, 'Description 2', 'DINAMIC', NULL, 
    140, NULL, 148, 182, 'STRING', 
    NULL, 'E', 'RIGHT', 'SELECT replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(upper(  nvl(CH.REMIT_TO_SUPPLIER_NAME, ch.VENDOR_NAME) ), CHR(13), null), CHR(10),null), ''Ú'', ''U''), ''Ó'', ''O''), ''Í'', ''I''), ''É'', ''E''), ''Á'', ''A''),''À'',''A''),''È'',''E''),''Ì'',''I''),''Ò'',''O''),''Ù'',''U''),''Ñ'',''N''),''#'','' ''),''@'','' ''),''^'','' ''),''*'','' ''),''%'','' ''),''&'','' ''),''\'','' ''),''|'','' ''),''!'','' ''),''~'','' ''),''?'','' ''),''}'','' ''),''{'','' ''),''['','' ''),'']'','' ''),chr(39),'' ''),''`'','' ''),''/'','' ''),''Ü'',''U'') vendor   FROM ap.AP_CHECKS_ALL CH   where ch.CHECK_ID = :IDCHECK', 'Y', 
    'TRX', 3129, TO_DATE('04/30/2013 15:13:11', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/27/2013 16:24:37', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (7, 2, 'Espacio', 'CONSTANT', '\N', 
    30, NULL, NULL, NULL, 'STRING', 
    NULL, NULL, NULL, NULL, NULL, 
    'TRX', 3129, TO_DATE('04/22/2013 11:34:28', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/24/2013 08:58:09', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (8, 2, 'Monto', 'DINAMIC', NULL, 
    40, NULL, NULL, NULL, 'STRING', 
    NULL, NULL, NULL, 'select trim(to_char(ch.AMOUNT,''9999999999.99''))   from apps.ap_checks_all ch  where ch.CHECK_ID = :IDCHECK    and PAYMENT_METHOD_CODE = ''EFT''    AND CH.VOID_DATE IS NULL', NULL, 
    'TRX', 3129, TO_DATE('04/22/2013 11:34:28', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/22/2013 11:34:28', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (9, 2, 'Fecha', 'DINAMIC', NULL, 
    50, NULL, NULL, NULL, 'STRING', 
    NULL, NULL, NULL, 'select to_char(ch.CHECK_DATE,''DDMMYYYY'') from ap_checks_all ch where ch.CHECK_ID = :IDCHECK', NULL, 
    'TRX', 3129, TO_DATE('04/22/2013 11:35:42', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('04/22/2013 11:35:42', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (10, 2, 'Descripcion', 'DINAMIC', NULL, 
    60, NULL, NULL, NULL, 'STRING', 
    NULL, NULL, NULL, 'SELECT SUBSTR(''Documentos: '' || LISTAGG ( IA.INVOICE_NUM, '', '') WITHIN GROUP (ORDER BY IA.INVOICE_NUM),1,165)          invoices  FROM AP_CHECKS_ALL CH, AP_INVOICE_PAYMENTS_ALL IV, AP_INVOICES_ALL IA WHERE     CH.CHECK_ID = :IDCHECK       AND CH.CHECK_ID = IV.CHECK_ID       AND IV.INVOICE_ID = IA.INVOICE_ID', NULL, 
    'TRX', 3129, TO_DATE('04/22/2013 11:35:42', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/17/2013 09:16:58', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (50, 3, 'Acount Type [for Citibank Accounts]', 'DINAMIC', NULL, 
    400, NULL, 632, 633, 'STRING', 
    NULL, NULL, NULL, 'SELECT decode(ATTRIBUTE12,''072'',decode(BANK_ACCOUNT_TYPE,''SAVING'',''02'',''SAVINGS'',''02'',''2'',''02'',''CHECKING'',''01'',''11'',BANK_ACCOUNT_TYPE)) BANK_ACCOUNT_TYPE  FROM (   SELECT SS.ATTRIBUTE12,           SS.ATTRIBUTE13,          eba.bank_account_num,          PIU.ORDER_OF_PREFERENCE,          EBA.BANK_ACCOUNT_TYPE     FROM ap.ap_supplier_sites_all ss,          ap.ap_suppliers sp,          iby.iby_external_payees_all epa,          iby.iby_pmt_instr_uses_all piu,          iby.iby_ext_bank_accounts eba,          ap.ap_checks_all ch,          apps.ce_banks_v ib,          ce.ce_bank_acct_uses_all ibu,          ce.ce_bank_accounts iba,          ce.ce_payment_documents idc    WHERE     CH.CHECK_ID = :IDCHECK          AND ss.org_id = CH.ORG_ID          AND SP.VENDOR_ID = CH.VENDOR_ID          AND CH.VENDOR_ID = SS.VENDOR_ID          AND ss.vendor_site_id = epa.supplier_site_id          AND epa.ext_payee_id = piu.ext_pmt_party_id          AND piu.instrument_id = eba.ext_bank_account_id          AND CH.PAYMENT_DOCUMENT_ID = iDC.PAYMENT_DOCUMENT_ID          AND idc.INTERNAL_BANK_ACCOUNT_ID = ibu.BANK_ACCOUNT_ID          AND ibu.BANK_ACCOUNT_ID = iba.BANK_ACCOUNT_ID          AND iba.BANK_ID = ib.BANK_PARTY_ID          AND ib.BANK_PARTY_ID = EBA.BANK_ID /*Esto es para que la cuenta que traiga sea del mimo banco*/          AND NVL (PIU.END_DATE, SYSDATE) >= SYSDATE ORDER BY ORDER_OF_PREFERENCE ASC) where rownum = 1', NULL, 
    'TRX', 3129, TO_DATE('05/03/2013 14:25:21', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/13/2013 09:39:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (51, 3, 'Transaction Delivery Method', 'DINAMIC', NULL, 
    410, NULL, 634, 636, 'STRING', 
    NULL, NULL, NULL, 'SELECT SS.ATTRIBUTE13 FROM AP_SUPPLIERS SUP, AP_SUPPLIER_SITES SS, AP_CHECKS_ALL CH WHERE SUP.VENDOR_ID = SS.VENDOR_ID   AND CH.VENDOR_SITE_ID = SS.VENDOR_SITE_ID   AND CH.CHECK_ID = :IDCHECK', NULL, 
    'TRX', 3129, TO_DATE('05/03/2013 14:25:21', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/03/2013 14:25:21', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (52, 3, 'Collection Title ID', 'CONSTANT', '\E', 
    420, NULL, 637, 686, 'STRING', 
    NULL, 'E', 'LEFT', NULL, 'Y', 
    'TRX', 3129, TO_DATE('05/03/2013 14:25:21', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/03/2013 14:25:21', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (53, 3, 'Third Party Activity Code', 'CONSTANT', '\E', 
    430, NULL, 687, 691, 'STRING', 
    NULL, 'E', 'RIGHT', NULL, 'Y', 
    'TRX', 3129, TO_DATE('05/03/2013 14:25:21', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/03/2013 14:25:21', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (54, 3, 'Third Party E-Mail Address', 'CONSTANT', '\E', 
    440, NULL, 692, 741, 'STRING', 
    NULL, 'E', 'RIGHT', NULL, NULL, 
    'TRX', 3129, TO_DATE('05/03/2013 14:25:21', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/03/2013 14:25:21', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (55, 3, 'Maximum Payment Amount', 'CONSTANT', '999999999999999', 
    450, NULL, 742, 756, 'STRING', 
    NULL, NULL, NULL, NULL, NULL, 
    'TRX', 3129, TO_DATE('05/03/2013 14:25:21', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/03/2013 14:25:21', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (56, 3, 'Update Type', 'CONSTANT', '1', 
    460, NULL, 757, 757, 'STRING', 
    NULL, NULL, NULL, NULL, NULL, 
    'TRX', 3129, TO_DATE('05/03/2013 14:25:21', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/03/2013 14:25:21', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (57, 3, 'Check Or Transference Number', 'CONSTANT', '\E', 
    470, NULL, 758, 768, 'STRING', 
    NULL, NULL, NULL, NULL, NULL, 
    'TRX', 3129, TO_DATE('05/03/2013 14:25:21', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/03/2013 14:25:21', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (58, 3, 'Printed Check Flag', 'CONSTANT', '\E', 
    480, NULL, 769, 769, 'STRING', 
    NULL, NULL, NULL, NULL, NULL, 
    'TRX', 3129, TO_DATE('05/03/2013 14:25:21', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/03/2013 14:25:55', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (59, 3, 'Match Pay Flag', 'CONSTANT', '\E', 
    490, NULL, 770, 770, 'STRING', 
    NULL, NULL, NULL, NULL, NULL, 
    'TRX', 3129, TO_DATE('05/03/2013 14:25:21', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/03/2013 14:25:55', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (60, 3, 'Blank Characters', 'CONSTANT', '\E', 
    500, NULL, 771, 1024, 'STRING', 
    NULL, NULL, NULL, NULL, NULL, 
    'TRX', 3129, TO_DATE('05/03/2013 14:25:21', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/03/2013 14:25:55', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (61, 3, 'Record type', 'CONSTANT', 'VOI', 
    510, NULL, 1, 3, 'STRING', 
    NULL, NULL, NULL, NULL, NULL, 
    'DETAIL', 3129, TO_DATE('05/03/2013 14:44:40', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/03/2013 14:44:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (62, 3, 'Customer Country Code', 'CONSTANT', '222', 
    520, NULL, 4, 6, 'STRING', 
    NULL, NULL, NULL, NULL, NULL, 
    'DETAIL', 3129, TO_DATE('05/03/2013 14:44:40', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/03/2013 14:44:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (63, 3, 'Customer Account Number', 'DINAMIC', NULL, 
    530, NULL, 7, 16, 'STRING', 
    NULL, NULL, NULL, 'select REPLACE(inba.BANK_ACCOUNT_NUM,''-'','''')   from  apps.ap_checks_all          chk       , apps.CE_BANK_ACCT_USES_ALL  bua        ,apps.ce_bank_accounts       inba        , apps.CE_BANK_BRANCHES_V     BB  where  1=1    and  bua.BANK_ACCT_USE_ID   = chk.CE_BANK_ACCT_USE_ID    and  bua.BANK_ACCOUNT_ID    = inba.BANK_ACCOUNT_ID    and  bb.BRANCH_PARTY_ID     = inba.BANK_BRANCH_ID    AND  CHK.CHECK_ID = :IDCHECK', NULL, 
    'DETAIL', 3129, TO_DATE('05/03/2013 14:44:40', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/03/2013 14:44:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (64, 3, 'Transaction Reference', 'DINAMIC', NULL, 
    540, NULL, 17, 31, 'STRING', 
    NULL, NULL, NULL, 'select ch.doc_sequence_value FROM    ap_checks_all    ch WHERE CH.CHECK_ID =  :IDCHECK', NULL, 
    'DETAIL', 3129, TO_DATE('05/03/2013 14:44:40', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/03/2013 14:44:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (65, 3, 'Transaction Sequence Number', 'SEQUENCE1', NULL, 
    550, NULL, 32, 39, 'NUMBER', 
    '999999999', '0', 'LEFT', NULL, NULL, 
    'DETAIL', 3129, TO_DATE('05/03/2013 14:44:40', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/06/2013 13:43:32', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (66, 3, 'Sub-sequence', 'SEQUENCE2', NULL, 
    560, NULL, 40, 43, 'NUMBER', 
    '999999999', '0', 'LEFT', NULL, NULL, 
    'DETAIL', 3129, TO_DATE('05/03/2013 14:44:40', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/06/2013 13:43:32', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (67, 3, 'Invoice Detail Description', 'DINAMIC', NULL, 
    570, NULL, 44, 118, 'STRING', 
    NULL, NULL, NULL, 'SELECT  ''INVOICE: ''|| IA.INVOICE_NUM || '' - AMOUNT: '' || IA.INVOICE_AMOUNT DETAIL   FROM  APPS.AP_INVOICES_ALL  IA        ,APPS.AP_INVOICE_PAYMENTS_ALL  IPA        ,AP_CHECKS_ALL     CH  WHERE CH.CHECK_ID = IPA.CHECK_ID    AND IPA.INVOICE_ID = IA.INVOICE_ID    AND CH.CHECK_ID = :IDCHECK    AND IA.INVOICE_ID = :INVOICEID', NULL, 
    'DETAIL', 3129, TO_DATE('05/03/2013 14:44:40', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/03/2013 14:44:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (68, 3, 'Blank Characters', 'CONSTANT', '\E', 
    580, NULL, 119, 250, 'STRING', 
    NULL, NULL, NULL, NULL, NULL, 
    'DETAIL', 3129, TO_DATE('05/03/2013 14:44:40', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/03/2013 14:44:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (69, 3, 'Record Type', 'CONSTANT', 'TRL', 
    600, NULL, 1, 3, 'STRING', 
    NULL, NULL, NULL, NULL, NULL, 
    'FOOTER', 3129, TO_DATE('05/03/2013 14:52:57', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/03/2013 14:52:57', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (70, 3, 'Number of transactions', 'DINAMIC', NULL, 
    610, NULL, 4, 18, 'STRING', 
    NULL, '0', 'LEFT', 'SELECT COUNT (CH.CHECK_ID) CHECKS   FROM AP_CHECKS_ALL CH  WHERE 1 = 1    AND TRUNC (CH.CHECK_DATE) >=           TRUNC (TO_DATE (:P_START_DATE, ''YYYY/MM/DD HH24:MI:SS'')) /*NOT NULL*/    AND TRUNC (CH.CHECK_DATE) <=             TRUNC (TO_DATE (:P_END_DATE, ''YYYY/MM/DD HH24:MI:SS'')) /*NOT NULL*/    AND CH.PAYMENT_DOCUMENT_ID = :PAY_DOCUMENT /*NOT NULL*/    AND CH.AMOUNT BETWEEN NVL (:BASE_AMOUNT, CH.AMOUNT)                      AND NVL (:TOP_AMOUNT, CH.AMOUNT) /* PSBLY NULL*/    AND NVL (CH.CHECKRUN_ID, 1) =                          NVL (NVL (:IDCHECKRUN, CH.CHECKRUN_ID), 1) /* CASE 1*/    AND NVL (CH.DOC_SEQUENCE_VALUE, 1) >=                    NVL (NVL (:P_DOC_INI, CH.DOC_SEQUENCE_VALUE), 1) /* CASE 2*/    AND NVL (CH.DOC_SEQUENCE_VALUE, 1) <=                    NVL (NVL (:P_DOC_FIN, CH.DOC_SEQUENCE_VALUE), 1) /* CASE 2*/    AND CH.PAYMENT_METHOD_CODE = ''EFT''    AND NVL (CH.ATTRIBUTE14, ''NEW'') = ''NEW''    AND CH.VOID_DATE IS NULL', 'Y', 
    'FOOTER', 3129, TO_DATE('05/03/2013 14:52:57', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/06/2013 13:27:52', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BOLINF.XX_SV_AP_EPAYMENT_DETAIL
   (ID_FILE_FORMAT, ID_MASTER, FIELD_NAME, TYPE_VALUE, CONSTANT_VALUE, 
    SECUENCE, MAX_VALUE_LENGHT, START_POSITION, END_POSITION, DATA_TYPE, 
    FORMAT, PADDING_CHARACTER, DIRECTION_PADDING, SQL_STATEMENT, NEEDS_PADDING, 
    PART_OF_FILE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 Values
   (71, 3, 'Total transaction amount', 'DINAMIC', NULL, 
    620, NULL, 19, 33, 'STRING', 
    NULL, '0', 'LEFT', 'SELECT SUM (CH.AMOUNT)*100   FROM AP_CHECKS_ALL CH  WHERE 1 = 1    AND TRUNC (CH.CHECK_DATE) >=           TRUNC (TO_DATE (:P_START_DATE, ''YYYY/MM/DD HH24:MI:SS'')) /*NOT NULL*/    AND TRUNC (CH.CHECK_DATE) <=             TRUNC (TO_DATE (:P_END_DATE, ''YYYY/MM/DD HH24:MI:SS'')) /*NOT NULL*/    AND CH.PAYMENT_DOCUMENT_ID = :PAY_DOCUMENT /*NOT NULL*/    AND CH.AMOUNT BETWEEN NVL (:BASE_AMOUNT, CH.AMOUNT)                      AND NVL (:TOP_AMOUNT, CH.AMOUNT) /* PSBLY NULL*/    AND NVL (CH.CHECKRUN_ID, 1) =                          NVL (NVL (:IDCHECKRUN, CH.CHECKRUN_ID), 1) /* CASE 1*/    AND NVL (CH.DOC_SEQUENCE_VALUE, 1) >=                    NVL (NVL (:P_DOC_INI, CH.DOC_SEQUENCE_VALUE), 1) /* CASE 2*/    AND NVL (CH.DOC_SEQUENCE_VALUE, 1) <=                    NVL (NVL (:P_DOC_FIN, CH.DOC_SEQUENCE_VALUE), 1) /* CASE 2*/    AND CH.PAYMENT_METHOD_CODE = ''EFT''    AND NVL (CH.ATTRIBUTE14, ''NEW'') = ''NEW''    AND CH.VOID_DATE IS NULL', NULL, 
    'FOOTER', 3129, TO_DATE('05/03/2013 14:52:57', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/06/2013 13:27:52', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
