ALTER TABLE BOLINF.XX_SV_AP_EPAYMENT_MASTER
 DROP PRIMARY KEY CASCADE;
DROP TABLE BOLINF.XX_SV_AP_EPAYMENT_MASTER CASCADE CONSTRAINTS;

CREATE TABLE BOLINF.XX_SV_AP_EPAYMENT_MASTER
(
  ID_MASTER               NUMBER                NOT NULL,
  DELIMITER               VARCHAR2(1 BYTE),
  MAX_VALUE_LENGTH        NUMBER,
  FORMAT_NAME             VARCHAR2(150 BYTE)    NOT NULL,
  TYPE_TEXT_FILE          VARCHAR2(50 BYTE),
  CE_BANK_ACCOUNT_USE_ID  NUMBER,
  CREATED_BY              NUMBER,
  CREATION_DATE           DATE,
  LAST_UPDATED_BY         NUMBER,
  LAST_UPDATE_DATE        DATE,
  ENABLE                  VARCHAR2(1 BYTE)
)
TABLESPACE XBOLDATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX BOLINF.XX_SV_AP_EPAYMENT_MASTER_U1 ON BOLINF.XX_SV_AP_EPAYMENT_MASTER
(ID_MASTER)
LOGGING
TABLESPACE XBOLINDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM XX_SV_AP_EPAYMENT_MASTER;

CREATE PUBLIC SYNONYM XX_SV_AP_EPAYMENT_MASTER FOR BOLINF.XX_SV_AP_EPAYMENT_MASTER;


ALTER TABLE BOLINF.XX_SV_AP_EPAYMENT_MASTER ADD (
  CONSTRAINT XX_SV_AP_EPAYMENT_MASTER_PK
 PRIMARY KEY
 (ID_MASTER));

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON BOLINF.XX_SV_AP_EPAYMENT_MASTER TO APPS WITH GRANT OPTION;

GRANT SELECT ON BOLINF.XX_SV_AP_EPAYMENT_MASTER TO RAC_ACCNT;

GRANT SELECT ON BOLINF.XX_SV_AP_EPAYMENT_MASTER TO RAC_COM;

GRANT SELECT ON BOLINF.XX_SV_AP_EPAYMENT_MASTER TO RAC_FIN;

GRANT SELECT ON BOLINF.XX_SV_AP_EPAYMENT_MASTER TO RAC_SUP;


SET DEFINE OFF;
Insert into BOLINF.XX_SV_AP_EPAYMENT_MASTER
   (ID_MASTER, DELIMITER, MAX_VALUE_LENGTH, FORMAT_NAME, TYPE_TEXT_FILE, 
    CE_BANK_ACCOUNT_USE_ID, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, 
    ENABLE)
 Values
   (1, 'T', NULL, 'Net banking (CITIBANK)', 'DELIMITED', 
    994538, 3129, TO_DATE('04/15/2013 09:29:21', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/27/2013 15:53:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'Y');
Insert into BOLINF.XX_SV_AP_EPAYMENT_MASTER
   (ID_MASTER, DELIMITER, MAX_VALUE_LENGTH, FORMAT_NAME, TYPE_TEXT_FILE, 
    CE_BANK_ACCOUNT_USE_ID, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, 
    ENABLE)
 Values
   (3, NULL, NULL, 'Citibank Paylink', 'POSITIONS', 
    994538, 3129, TO_DATE('04/29/2013 13:11:40', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/27/2013 15:53:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'Y');
Insert into BOLINF.XX_SV_AP_EPAYMENT_MASTER
   (ID_MASTER, DELIMITER, MAX_VALUE_LENGTH, FORMAT_NAME, TYPE_TEXT_FILE, 
    CE_BANK_ACCOUNT_USE_ID, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, 
    ENABLE)
 Values
   (2, ';', NULL, 'Pago electronico Banco Agricola', 'DELIMITED', 
    994489, 3129, TO_DATE('04/22/2013 11:34:28', 'MM/DD/YYYY HH24:MI:SS'), 3129, TO_DATE('05/20/2013 10:00:15', 'MM/DD/YYYY HH24:MI:SS'), 
    'Y');
COMMIT;
