SET DEFINE OFF;
DROP TABLE BOLINF.XX_AP_EFT_FORMAT_DEFINITIONS CASCADE CONSTRAINTS
/

CREATE TABLE BOLINF.XX_AP_EFT_FORMAT_DEFINITIONS
(
  DEFINITION_ID      NUMBER,
  FORMAT_ID          NUMBER,
  FIELD_NAME         VARCHAR2(150 BYTE),
  TYPE_VALUE         VARCHAR2(50 BYTE),
  CONSTANT_VALUE     VARCHAR2(50 BYTE),
  SECUENCE           NUMBER,
  START_POSITION     NUMBER,
  END_POSITION       NUMBER,
  DATA_TYPE          VARCHAR2(50 BYTE),
  FORMAT_MODEL       VARCHAR2(50 BYTE),
  PADDING_CHARACTER  NUMBER,
  DIRECTION_PADDING  VARCHAR2(50 BYTE),
  SQL_STATEMENT      VARCHAR2(4000 BYTE),
  NEEDS_PADDING      VARCHAR2(1 BYTE),
  PART_OF_FILE       VARCHAR2(50 BYTE),
  CREATED_BY         NUMBER,
  CREATION_DATE      DATE,
  LAST_UPDATED_BY    NUMBER,
  LAST_UPDATE_DATE   DATE
)
TABLESPACE XBOLDATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

CREATE OR REPLACE PUBLIC SYNONYM XX_AP_EFT_FORMAT_DEFINITIONS FOR BOLINF.XX_AP_EFT_FORMAT_DEFINITIONS
/
/
exit
/