ALTER TABLE BOLINF.XX_SV_AP_EPAYMENT_MASTER
 DROP PRIMARY KEY CASCADE;
DROP TABLE BOLINF.XX_SV_AP_EPAYMENT_MASTER CASCADE CONSTRAINTS;

CREATE TABLE BOLINF.XX_SV_AP_EPAYMENT_MASTER
(
  ID_MASTER               NUMBER                NOT NULL,
  DELIMITER               VARCHAR2(1 BYTE),
  MAX_VALUE_LENGTH        NUMBER,
  FORMAT_NAME             VARCHAR2(150 BYTE)    NOT NULL,
  TYPE_TEXT_FILE          VARCHAR2(50 BYTE),
  CE_BANK_ACCOUNT_USE_ID  NUMBER,
  CREATED_BY              NUMBER,
  CREATION_DATE           DATE,
  LAST_UPDATED_BY         NUMBER,
  LAST_UPDATE_DATE        DATE,
  ENABLE                  VARCHAR2(1 BYTE)
)
TABLESPACE XBOLDATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX BOLINF.XX_SV_AP_EPAYMENT_MASTER_U1 ON BOLINF.XX_SV_AP_EPAYMENT_MASTER
(ID_MASTER)
LOGGING
TABLESPACE XBOLDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



CREATE OR REPLACE PUBLIC SYNONYM XX_SV_AP_EPAYMENT_MASTER FOR BOLINF.XX_SV_AP_EPAYMENT_MASTER;


ALTER TABLE BOLINF.XX_SV_AP_EPAYMENT_MASTER ADD (
  CONSTRAINT XX_SV_AP_EPAYMENT_MASTER_PK
 PRIMARY KEY
 (ID_MASTER));

/
create or replace public synonym XX_SV_AP_EPAYMENT_MASTER for bolinf.XX_SV_AP_EPAYMENT_MASTER;
/
grant all on XX_SV_AP_EPAYMENT_MASTER to apps with grant option;

/
exit
/