ALTER TABLE BOLINF.XX_SV_AP_EPAYMENT_DETAIL
 DROP PRIMARY KEY CASCADE;
DROP TABLE BOLINF.XX_SV_AP_EPAYMENT_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE BOLINF.XX_SV_AP_EPAYMENT_DETAIL
(
  ID_FILE_FORMAT     NUMBER,
  ID_MASTER          NUMBER,
  FIELD_NAME         VARCHAR2(150 BYTE),
  TYPE_VALUE         VARCHAR2(50 BYTE),
  CONSTANT_VALUE     VARCHAR2(4000 BYTE),
  SECUENCE           NUMBER,
  MAX_VALUE_LENGHT   NUMBER,
  START_POSITION     NUMBER,
  END_POSITION       NUMBER,
  DATA_TYPE          VARCHAR2(50 BYTE),
  FORMAT             VARCHAR2(50 BYTE),
  PADDING_CHARACTER  VARCHAR2(1 BYTE),
  DIRECTION_PADDING  VARCHAR2(50 BYTE),
  SQL_STATEMENT      VARCHAR2(4000 BYTE),
  NEEDS_PADDING      VARCHAR2(1 BYTE),
  PART_OF_FILE       VARCHAR2(50 BYTE),
  CREATED_BY         NUMBER,
  CREATION_DATE      DATE,
  LAST_UPDATED_BY    NUMBER,
  LAST_UPDATE_DATE   DATE
)
TABLESPACE XBOLDATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX BOLINF.XX_SV_AP_EPAYMENT_DETAIL_U1 ON BOLINF.XX_SV_AP_EPAYMENT_DETAIL
(ID_FILE_FORMAT)
LOGGING
TABLESPACE XBOLDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM XX_SV_AP_EPAYMENT_DETAIL FOR BOLINF.XX_SV_AP_EPAYMENT_DETAIL;


ALTER TABLE BOLINF.XX_SV_AP_EPAYMENT_DETAIL ADD (
  CONSTRAINT XX_SV_AP_EPAYMENT_DETAIL_U1
 PRIMARY KEY
 (ID_FILE_FORMAT)
    USING INDEX 
    TABLESPACE XBOLDATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          1M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

/
create or replace public synonym XX_SV_AP_EPAYMENT_DETAIL for bolinf.XX_SV_AP_EPAYMENT_DETAIL;
/
grant all on XX_SV_AP_EPAYMENT_DETAIL to apps with grant option;

/
exit
/