CREATE TABLE BOLINF.XX_AP_EFT_FORMAT_DEFINITIONS
(
  DEFINITION_ID      NUMBER,            --1
  FORMAT_ID          NUMBER,            --2
  FIELD_NAME         VARCHAR2(150 BYTE),    --3
  TYPE_VALUE         VARCHAR2(50 BYTE),     --4
  CONSTANT_VALUE     VARCHAR2(50 BYTE),     --5
  SECUENCE           NUMBER,        --6
  START_POSITION     NUMBER,        --7
  END_POSITION       NUMBER,        --8
  DATA_TYPE          VARCHAR2(50 BYTE), --9
  FORMAT_MODEL       VARCHAR2(50 BYTE), --10
  PADDING_CHARACTER  NUMBER,    -- 11
  DIRECTION_PADDING  VARCHAR2(50 BYTE), --12
  SQL_STATEMENT      VARCHAR2(4000 BYTE),   --13
  PART_OF_FILE       VARCHAR2(50 BYTE),--14
  CREATED_BY         NUMBER,--15
  CREATION_DATE      DATE,--16
  LAST_UPDATED_BY    NUMBER,--17
  LAST_UPDATE_DATE   DATE--18
)
TABLESPACE XBOLDATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/
exit
/
