SET DEFINE OFF;
DROP TABLE BOLINF.XX_AP_EFT_FORMATS CASCADE CONSTRAINTS
/

CREATE TABLE BOLINF.XX_AP_EFT_FORMATS
(
  FORMAT_ID         NUMBER                      NOT NULL,
  FORMAT_NAME       VARCHAR2(150 BYTE)          NOT NULL,
  FORMAT_TYPE       VARCHAR2(50 BYTE),
  ASCII_DELIMITER   NUMBER,
  FILE_EXTENSION    VARCHAR2(10 BYTE),
  ENABLE_FLAG       VARCHAR2(1 BYTE),
  CREATED_BY        NUMBER,
  CREATION_DATE     DATE,
  LAST_UPDATED_BY   NUMBER,
  LAST_UPDATE_DATE  DATE
)
TABLESPACE XBOLDATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


DROP PUBLIC SYNONYM XX_AP_EFT_FORMATS
/

CREATE PUBLIC SYNONYM XX_AP_EFT_FORMATS FOR BOLINF.XX_AP_EFT_FORMATS
/
